# Generated by Django 2.0.2 on 2018-02-07 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('player_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('fullName', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=3)),
                ('dob', models.DateField()),
                ('nationality', models.CharField(max_length=50)),
                ('currentTeam', models.CharField(max_length=50)),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
            ],
        ),
    ]
