# Generated by Django 2.0.2 on 2018-02-07 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='currentTeam',
            new_name='current_Team',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='fullName',
            new_name='full_Name',
        ),
    ]
