# Generated by Django 2.0.2 on 2018-02-07 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0004_auto_20180206_2211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='full_Name',
            new_name='full_name',
        ),
    ]
