# Generated by Django 2.0.2 on 2018-02-07 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0008_player_portrait'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='portrait',
            field=models.ImageField(blank=True, default='', null=True, upload_to='resources/players/'),
        ),
    ]
