# Generated by Django 2.0.2 on 2018-02-07 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0009_auto_20180207_1433'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('competition_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('logo', models.ImageField(blank=True, default='', upload_to='resources/compeitions/')),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('season_id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('competition_id', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='football.Competition')),
                ('teams', models.ManyToManyField(to='football.Team')),
            ],
        ),
    ]
