# Generated by Django 2.0.2 on 2018-02-07 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0011_auto_20180207_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixture',
            name='pressure',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='windchill',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3),
        ),
    ]
