# Generated by Django 2.0.2 on 2018-02-07 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0012_auto_20180207_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixture',
            name='windchill',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
    ]
