# Generated by Django 2.0.2 on 2018-02-08 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0013_auto_20180207_1801'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minute_in', models.IntegerField(default=0)),
                ('minute_out', models.IntegerField(default=90)),
                ('yellow_cards', models.IntegerField(default=0)),
                ('red_cards', models.IntegerField(default=0)),
                ('shots', models.IntegerField(default=0)),
                ('shots_on_target', models.IntegerField(default=0)),
                ('shots_blocked', models.IntegerField(default=0)),
                ('crossbar', models.IntegerField(default=0)),
                ('touches', models.IntegerField(default=0)),
                ('dribbles_attempted', models.IntegerField(default=0)),
                ('dribbles_won', models.IntegerField(default=0)),
                ('fouled', models.IntegerField(default=0)),
                ('offsides', models.IntegerField(default=0)),
                ('possession', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('dispossessed', models.IntegerField(default=0)),
                ('passes', models.IntegerField(default=0)),
                ('key_passes', models.IntegerField(default=0)),
                ('pass_accuracy', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('crosses', models.IntegerField(default=0)),
                ('accurate_crosses', models.IntegerField(default=0)),
                ('corners', models.IntegerField(default=0)),
                ('corner_accuracy', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('long_balls', models.IntegerField(default=0)),
                ('accurate_long_balls', models.IntegerField(default=0)),
                ('through_balls', models.IntegerField(default=0)),
                ('accurate_through_balls', models.IntegerField(default=0)),
                ('defensive_aerials', models.IntegerField(default=0)),
                ('offensive_aerials', models.IntegerField(default=0)),
                ('aerials_won', models.IntegerField(default=0)),
                ('total_tackles', models.IntegerField(default=0)),
                ('successful_tackles', models.IntegerField(default=0)),
                ('interceptions', models.IntegerField(default=0)),
                ('dribbled_past', models.IntegerField(default=0)),
                ('clearances', models.IntegerField(default=0)),
                ('blocked_shots', models.IntegerField(default=0)),
                ('fouls_committed', models.IntegerField(default=0)),
                ('fixture_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football.Fixture')),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football.Player')),
            ],
        ),
    ]
