# Generated by Django 2.0.2 on 2018-02-08 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0014_statistics'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='player',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
