# Generated by Django 2.0.2 on 2018-02-25 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0016_team_crest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='portrait',
            field=models.ImageField(blank=True, default='', null=True, upload_to='C:\\Users\\Subject 18\\Football\\Development\\barcaresources/players/'),
        ),
    ]
