# Generated by Django 2.0.2 on 2018-02-25 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0017_auto_20180224_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='portrait',
            field=models.ImageField(blank=True, default='', null=True, upload_to='resources/players/'),
        ),
    ]
