# Generated by Django 2.0.2 on 2018-02-25 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0018_auto_20180224_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='portrait',
            field=models.ImageField(blank=True, default='', null=True, upload_to='players/'),
        ),
    ]
