# Generated by Django 2.0.2 on 2018-02-25 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0021_auto_20180225_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='competition_id',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='seasons', to='football.Competition'),
        ),
    ]
