# Generated by Django 2.0.2 on 2018-02-25 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0022_auto_20180225_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixture',
            name='away_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='extra_time',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='home_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='penalty_shootout',
            field=models.BooleanField(default=False),
        ),
    ]
