# Generated by Django 2.0.2 on 2018-02-26 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0023_auto_20180225_1819'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamStanding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('draws', models.IntegerField(default=0)),
                ('overtimeWins', models.IntegerField(default=0)),
                ('overtimeLosses', models.IntegerField(default=0)),
                ('goalsForced', models.IntegerField(default=0)),
                ('goalsAllowed', models.IntegerField(default=0)),
                ('points', models.IntegerField(default=0)),
                ('winStreak', models.IntegerField(default=0)),
                ('winDrawStreak', models.IntegerField(default=0)),
                ('drawStreak', models.IntegerField(default=0)),
                ('drawLossStreak', models.IntegerField(default=0)),
                ('lossStreak', models.IntegerField(default=0)),
                ('cleanSheetStreak', models.IntegerField(default=0)),
                ('failedToScoreStreak', models.IntegerField(default=0)),
            ],
        ),
        migrations.RenameField(
            model_name='season',
            old_name='competition_id',
            new_name='competition',
        ),
        migrations.AddField(
            model_name='teamstanding',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standings', to='football.Season'),
        ),
        migrations.AddField(
            model_name='teamstanding',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standings', to='football.Team'),
        ),
    ]
