# Generated by Django 2.0.2 on 2018-02-26 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0024_auto_20180226_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixture',
            name='wind_direction',
            field=models.CharField(choices=[('N', 'North'), ('NNE', 'North-Northeast'), ('NE', 'Northeast'), ('ENE', 'East-Northeast'), ('E', 'East'), ('ESE', 'East-Southeast'), ('SE', 'Southeast'), ('SSE', 'South-Southeast'), ('S', 'South'), ('SSW', 'South-Southwest'), ('SW', 'Southwest'), ('WSW', 'West-Southwest'), ('W', 'West'), ('WNW', 'West-Northwest'), ('NW', 'Northwest'), ('NNW', 'North-Northwest'), ('V', 'Variable'), ('C', 'Calm')], default='C', max_length=3),
        ),
    ]
