# Generated by Django 2.0.2 on 2018-02-26 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0025_auto_20180226_1404'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teamstanding',
            old_name='cleanSheetStreak',
            new_name='clean_sheet_streak',
        ),
        migrations.RenameField(
            model_name='teamstanding',
            old_name='drawLossStreak',
            new_name='draw_loss_streak',
        ),
        migrations.RenameField(
            model_name='teamstanding',
            old_name='drawStreak',
            new_name='draw_streak',
        ),
        migrations.RenameField(
            model_name='teamstanding',
            old_name='failedToScoreStreak',
            new_name='failed_to_score_streak',
        ),
        migrations.RenameField(
            model_name='teamstanding',
            old_name='goalsAllowed',
            new_name='goals_allowed',
        ),
        migrations.RenameField(
            model_name='teamstanding',
            old_name='goalsForced',
            new_name='goals_forced',
        ),
        migrations.RenameField(
            model_name='teamstanding',
            old_name='lossStreak',
            new_name='loss_streak',
        ),
        migrations.RenameField(
            model_name='teamstanding',
            old_name='overtimeLosses',
            new_name='overtime_losses',
        ),
        migrations.RenameField(
            model_name='teamstanding',
            old_name='overtimeWins',
            new_name='overtime_wins',
        ),
        migrations.RenameField(
            model_name='teamstanding',
            old_name='winDrawStreak',
            new_name='win_draw_streak',
        ),
        migrations.RenameField(
            model_name='teamstanding',
            old_name='winStreak',
            new_name='win_streak',
        ),
    ]
