# Generated by Django 2.0.2 on 2018-02-26 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0026_auto_20180226_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamstanding',
            name='id',
        ),
        migrations.AddField(
            model_name='teamstanding',
            name='team_standing_id',
            field=models.CharField(default='undefined', max_length=50, primary_key=True, serialize=False),
        ),
    ]
