# Generated by Django 2.0.2 on 2018-02-26 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0027_auto_20180226_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamstanding',
            name='games_played',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teamstanding',
            name='goal_difference',
            field=models.IntegerField(default=0),
        ),
    ]
