# Generated by Django 2.0.2 on 2018-03-08 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0028_auto_20180226_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamstanding',
            name='team_standing_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
