# Generated by Django 2.0.2 on 2018-03-08 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0029_auto_20180308_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='competition_format',
            field=models.CharField(choices=[('league', 'l'), ('knockout', 'k')], default='l', max_length=1),
        ),
        migrations.AddField(
            model_name='competition',
            name='promotion_spots',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='competition',
            name='qualifying_spots',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='competition',
            name='relegation_spots',
            field=models.IntegerField(default=0),
        ),
    ]
