# Generated by Django 2.0.2 on 2018-03-08 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0031_auto_20180308_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixture',
            name='windchill',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True),
        ),
    ]
