# Generated by Django 2.0.2 on 2018-03-08 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0032_auto_20180308_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixture',
            name='humidity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='pressure',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='temperature',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='wind_speed',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True),
        ),
    ]
