# Generated by Django 2.0.2 on 2018-03-14 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0035_auto_20180314_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='logo',
            field=models.ImageField(blank=True, default='', upload_to='competitions/'),
        ),
    ]
