# Generated by Django 2.0.2 on 2018-03-14 15:32

from django.db import migrations, models
import football.models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0036_auto_20180314_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='logo',
            field=models.ImageField(blank=True, default='', upload_to=football.models.Competition.competition_path),
        ),
        migrations.AlterField(
            model_name='team',
            name='crest',
            field=models.ImageField(blank=True, default='', null=True, upload_to='teams/'),
        ),
    ]
