# Generated by Django 2.0.2 on 2018-03-14 15:33

from django.db import migrations, models
import football.models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0037_auto_20180314_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='crest',
            field=models.ImageField(blank=True, default='', null=True, upload_to=football.models.Team.team_path),
        ),
    ]
