# Generated by Django 2.0.2 on 2018-03-14 16:21

from django.db import migrations, models
import football.models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0038_auto_20180314_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='portrait',
            field=models.ImageField(blank=True, default='', null=True, upload_to=football.models.Player.player_path),
        ),
    ]
