# Generated by Django 2.0.2 on 2018-03-14 18:53

from django.db import migrations, models
import football.models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0039_auto_20180314_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='portrait',
            field=models.ImageField(blank=True, null=True, upload_to=football.models.Player.player_path),
        ),
    ]
