# Generated by Django 2.0.2 on 2018-05-11 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0040_auto_20180314_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='positions',
        ),
        migrations.AddField(
            model_name='player',
            name='primary_positions',
            field=models.ManyToManyField(related_name='primary_positions', to='football.Position'),
        ),
        migrations.AddField(
            model_name='player',
            name='secondary_positions',
            field=models.ManyToManyField(related_name='secondary_positions', to='football.Position'),
        ),
    ]
