# Generated by Django 2.0.2 on 2018-05-11 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0041_auto_20180510_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='secondary_positions',
            field=models.ManyToManyField(blank=True, related_name='secondary_positions', to='football.Position'),
        ),
    ]
