# Generated by Django 2.0.2 on 2018-05-15 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0042_auto_20180510_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistics',
            name='saves',
            field=models.IntegerField(default=0),
        ),
    ]
