# Generated by Django 2.0.2 on 2018-05-15 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0043_statistics_saves'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statistics',
            name='blocked_shots',
        ),
    ]
