# Generated by Django 2.0.2 on 2018-05-15 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0044_remove_statistics_blocked_shots'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistics',
            name='shots_bloc',
            field=models.IntegerField(default=0),
        ),
    ]
