# Generated by Django 2.0.2 on 2018-05-15 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0045_statistics_shots_bloc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statistics',
            name='shots_bloc',
        ),
    ]
