# Generated by Django 2.0.2 on 2018-05-15 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0046_remove_statistics_shots_bloc'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistics',
            name='blocked_shots',
            field=models.IntegerField(default=0),
        ),
    ]
