# Generated by Django 2.0.2 on 2018-05-15 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0047_statistics_blocked_shots'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistics',
            name='assists',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statistics',
            name='goals',
            field=models.IntegerField(default=0),
        ),
    ]
