# Generated by Django 2.0.2 on 2018-05-15 03:30

from django.db import migrations, models
import football.models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0048_auto_20180514_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=football.models.Venue.venue_path),
        ),
    ]
