# Generated by Django 2.0.2 on 2018-05-15 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0049_venue_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='FixtureEvent',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('G', 'Goal'), ('R', 'Red Card'), ('Y', 'Yellow Card')], default='G', max_length=1)),
                ('period', models.CharField(choices=[('1', '1st Half'), ('2', '2nd Half'), ('3', 'Overtime 1st Half'), ('4', 'Overtime 2nd Half'), ('5', 'Penalty Shootout')], default='1', max_length=1)),
                ('minute', models.IntegerField(default=0)),
                ('fixture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football.Fixture')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football.Player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football.Team')),
            ],
        ),
    ]
