# Generated by Django 2.0.2 on 2018-05-17 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0050_fixtureevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixtureevent',
            name='event_type',
            field=models.CharField(choices=[('G', 'Goal'), ('O', 'Own Goal'), ('P', 'Penalty'), ('R', 'Red Card'), ('Y', 'Yellow Card')], default='G', max_length=1),
        ),
    ]
