# Generated by Django 2.0.2 on 2018-05-17 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0051_auto_20180517_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football.Venue'),
        ),
    ]
