# Generated by Django 2.0.2 on 2018-05-17 20:00

from django.db import migrations, models
import football.models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0052_auto_20180517_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='portrait',
            field=models.ImageField(blank=True, default='', upload_to=football.models.Player.player_path),
        ),
    ]
