# Generated by Django 2.0.2 on 2018-05-17 21:35

from django.db import migrations, models
import football.models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0053_auto_20180517_1600'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fixture',
            old_name='season_id',
            new_name='season',
        ),
        migrations.AlterField(
            model_name='team',
            name='crest',
            field=models.ImageField(blank=True, default='', upload_to=football.models.Team.team_path),
        ),
        migrations.AlterField(
            model_name='venue',
            name='picture',
            field=models.ImageField(blank=True, default='', upload_to=football.models.Venue.venue_path),
        ),
    ]
