# Generated by Django 2.0.2 on 2018-05-17 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0054_auto_20180517_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixture',
            name='away_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_team', to='football.Team'),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='home_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_team', to='football.Team'),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='location',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='football.Venue'),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football.Season'),
        ),
    ]
