# Generated by Django 2.0.2 on 2019-08-26 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0060_auto_20180518_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='competition_format',
            field=models.CharField(choices=[('l', 'League'), ('k', 'Knockout')], default='l', help_text='League (Double round-robin), Knockout (Single elimination, two fixtures per round except final', max_length=1),
        ),
        migrations.AlterField(
            model_name='competition',
            name='promotion_limit',
            field=models.IntegerField(default=0, help_text='Final position for league promotion or competition entry'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='qualifying_limit',
            field=models.IntegerField(default=0, help_text='Final position for competition entry or qualification'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='relegation_limit',
            field=models.IntegerField(default=0, help_text='Number of relegation spots'),
        ),
        migrations.AlterField(
            model_name='player',
            name='dob',
            field=models.DateField(help_text='YYYY-MM-DD'),
        ),
        migrations.AlterField(
            model_name='player',
            name='height',
            field=models.IntegerField(help_text='cm'),
        ),
        migrations.AlterField(
            model_name='player',
            name='nationality',
            field=models.CharField(help_text='FIFA Country Code', max_length=3),
        ),
        migrations.AlterField(
            model_name='player',
            name='weight',
            field=models.IntegerField(help_text='kg'),
        ),
    ]
